### ISSUE TITLE
[Question] Integrating Minigl into Gosu?

### ISSUE THREAD

**Issue by rubyFeedback** [victords/minigl#3]
Hey there victords,

Have you asked the Gosu author to see whether miniGL could be integrated into Gosu as-is, to make the latter more convenient to use? I feel that many of the add-on projects, after some time, will fade away, which is why I think it would be better if Gosu as-is includes convenience add-ons.

**Comment by victords** [comment]
Hey there,

Thanks for expressing your interest in the library.

I think that wouldn't work out very well because the libraries kind of have different purposes - Gosu is more of a low level library than a game "framework"... which is what MiniGL proposes to be. In some ways, Gosu alone gives the developer more freedom to do things exactly how they want, while MiniGL assumes some conventions on how your project should be organized, in order to provide more productivity.

Lastly, the code architectures are quite different and I prefer to have more freedom to do the changes I want.

Regarding the risk of the project "fading away", I have no intention of stopping the updates anytime soon, so don't worry about that. :)
